version: "3.8"

volumes:
  postgres_data: {}

networks:
  internal: {}

services:
  postgres:
    image: postgres:17.2-alpine3.21
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: ${POSTGRES__DB}
      POSTGRES_USER: ${POSTGRES__USER}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD}
    ports:
      - "${POSTGRES__PORT}:5432"
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES__USER} -d ${POSTGRES__DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  bot:
    build: .
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES__HOST: postgres
      POSTGRES__PORT: 5432
      POSTGRES__USER: postgres
      POSTGRES__PASSWORD: psw
      POSTGRES__DB: db
      DATABASE_URL: postgresql+asyncpg://postgres:psw@postgres:5432/db
    networks:
      - internal
    command: >
      sh -c "
      alembic upgrade head &&
      python main.py"
