"""empty message

Revision ID: 7e0fbd5481a5
Revises: 015b864b0791
Create Date: 2025-04-28 22:21:20.519256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e0fbd5481a5'
down_revision: Union[str, None] = '015b864b0791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search_settings', 'engine_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('search_settings', 'drive_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search_settings', 'drive_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('search_settings', 'engine_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
